<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="theme-color" content="#0787bd">
    <title>Staff Login | AquaTrack</title>
    @vite(['resources/css/app.css', 'resources/js/app.js'])
</head>
<body class="min-h-screen bg-[#eefaff] font-sans text-slate-800 antialiased"><main class="grid min-h-screen lg:grid-cols-2"><section class="hidden overflow-hidden bg-[#0787bd] p-12 text-white lg:flex lg:flex-col"><a href="{{ route('home') }}" class="flex items-center gap-3"><span class="grid h-11 w-11 place-items-center rounded-2xl bg-white text-xl font-black text-[#0787bd]">A</span><span class="text-xl font-extrabold">AquaTrack</span></a><div class="my-auto max-w-md"><p class="text-sm font-bold tracking-[.18em] text-cyan-100">WATER STATION PORTAL</p><h1 class="mt-5 text-5xl font-black leading-tight">Every drop, managed with care.</h1><p class="mt-6 text-lg leading-8 text-cyan-50/85">Sign in to manage your station's orders, deliveries, sales, and inventory.</p></div><p class="text-sm text-cyan-100/75">Secure access for authorized station staff only.</p></section><section class="flex items-center justify-center px-6 py-12"><div class="w-full max-w-md"><a href="{{ route('home') }}" class="mb-12 flex items-center gap-3 lg:hidden"><span class="grid h-11 w-11 place-items-center rounded-2xl bg-[#0787bd] text-xl font-black text-white">A</span><span class="text-xl font-extrabold text-[#087ba9]">AquaTrack</span></a><p class="text-sm font-bold tracking-[.14em] text-[#0787bd]">WELCOME BACK</p><h2 class="mt-3 text-3xl font-black tracking-tight text-slate-900">Sign in to your account</h2><p class="mt-3 text-sm leading-6 text-slate-500">Use your station username and password to continue.</p><form method="POST" action="{{ route('login') }}" class="mt-9 space-y-5">@csrf<div><label for="username" class="text-sm font-bold text-slate-700">Username</label><input id="username" name="username" type="text" value="{{ old('username') }}" autocomplete="username" autofocus required class="mt-2 w-full rounded-xl border @error('username') border-red-400 @else border-slate-200 @enderror bg-white px-4 py-3.5 text-sm outline-none transition focus:border-cyan-500 focus:ring-4 focus:ring-cyan-100"><p class="mt-2 text-xs text-red-600">@error('username'){{ $message }}@enderror</p></div><div><label for="password" class="text-sm font-bold text-slate-700">Password</label><input id="password" name="password" type="password" autocomplete="current-password" required class="mt-2 w-full rounded-xl border border-slate-200 bg-white px-4 py-3.5 text-sm outline-none transition focus:border-cyan-500 focus:ring-4 focus:ring-cyan-100"></div><label class="flex items-center gap-2 text-sm text-slate-500"><input type="checkbox" name="remember" class="rounded border-slate-300 text-cyan-600 focus:ring-cyan-500"> Keep me signed in</label><button type="submit" class="w-full rounded-xl bg-[#0787bd] px-5 py-3.5 text-sm font-extrabold text-white shadow-lg shadow-cyan-700/20 transition hover:bg-[#066d99]">Sign in to dashboard</button></form><p class="mt-9 text-center text-sm text-slate-400">Need help? Contact your station administrator.</p></div></section></main></body>
</html>
