<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Dashboard | AquaTrack</title>
    @vite(['resources/css/app.css', 'resources/js/app.js'])
</head>
<body class="min-h-screen bg-[#f4f9fb] font-sans text-slate-800 antialiased">
    <div class="flex min-h-screen"><aside class="fixed inset-y-0 hidden w-72 flex-col bg-[#073b55] p-6 text-white lg:flex"><a href="{{ route('dashboard') }}" class="flex items-center gap-3"><span class="grid h-11 w-11 place-items-center rounded-2xl bg-[#23b5e7] text-xl font-black">A</span><span><span class="block text-xl font-extrabold">AquaTrack</span><span class="text-xs text-cyan-100/70">Water Station Portal</span></span></a><nav class="mt-12 space-y-2 text-sm font-semibold"><a href="#overview" class="block rounded-xl bg-white/15 px-4 py-3">Overview</a><a href="#orders" class="block rounded-xl px-4 py-3 text-cyan-100/75 transition hover:bg-white/10">Orders</a><a href="#deliveries" class="block rounded-xl px-4 py-3 text-cyan-100/75 transition hover:bg-white/10">Deliveries</a><a href="#inventory" class="block rounded-xl px-4 py-3 text-cyan-100/75 transition hover:bg-white/10">Inventory</a></nav><form action="{{ route('logout') }}" method="POST" class="mt-auto">@csrf<button class="w-full rounded-xl border border-white/20 px-4 py-3 text-left text-sm font-bold text-cyan-50 transition hover:bg-white/10">Sign out</button></form></aside>
        <main class="w-full lg:ml-72"><header class="flex h-20 items-center justify-between border-b border-slate-200 bg-white px-6 md:px-9"><div><p class="text-xs font-bold uppercase tracking-[.16em] text-[#0787bd]">{{ $user->role }}</p><h1 class="mt-1 text-lg font-extrabold text-slate-900">Good day, {{ $user->full_name }}</h1></div><div class="flex items-center gap-3"><span class="hidden text-right text-xs text-slate-400 sm:block">{{ now()->format('l, F j') }}</span><span class="grid h-10 w-10 place-items-center rounded-full bg-cyan-100 text-sm font-black text-cyan-700">{{ strtoupper(substr($user->full_name, 0, 1)) }}</span><form action="{{ route('logout') }}" method="POST" class="lg:hidden">@csrf<button class="text-sm font-bold text-[#087ba9]">Sign out</button></form></div></header>
            <div class="mx-auto max-w-7xl space-y-7 px-6 py-8 md:px-9" id="overview"><section class="relative overflow-hidden rounded-3xl bg-[#0787bd] p-7 text-white md:p-9"><div class="absolute -right-16 -top-20 h-60 w-60 rounded-full border-[25px] border-white/10"></div><p class="text-sm font-bold tracking-[.15em] text-cyan-100">STATION OVERVIEW</p><h2 class="relative mt-3 text-3xl font-black tracking-tight md:text-4xl">Your water station is ready for today.</h2><p class="relative mt-3 max-w-xl text-sm leading-6 text-cyan-50/85">Monitor live orders, delivery commitments, stock levels, and daily sales from one place.</p></section>
                <section class="grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><article class="rounded-2xl bg-white p-5 shadow-sm ring-1 ring-slate-100"><p class="text-sm font-semibold text-slate-500">Today's sales</p><p class="mt-2 text-2xl font-black">₱{{ number_format((float) $todaySales, 2) }}</p><p class="mt-4 text-xs font-bold text-emerald-600">Recorded today</p></article><article class="rounded-2xl bg-white p-5 shadow-sm ring-1 ring-slate-100"><p class="text-sm font-semibold text-slate-500">Orders today</p><p class="mt-2 text-2xl font-black">{{ $todayOrders }}</p><p class="mt-4 text-xs font-bold text-cyan-600">Refill & delivery requests</p></article><article class="rounded-2xl bg-white p-5 shadow-sm ring-1 ring-slate-100"><p class="text-sm font-semibold text-slate-500">Active products</p><p class="mt-2 text-2xl font-black">{{ $activeProducts }}</p><p class="mt-4 text-xs font-bold text-violet-600">Available for sale</p></article><article class="rounded-2xl bg-white p-5 shadow-sm ring-1 ring-slate-100"><p class="text-sm font-semibold text-slate-500">Stock alerts</p><p class="mt-2 text-2xl font-black">{{ $lowStockItems->count() }}</p><p class="mt-4 text-xs font-bold text-amber-600">At reorder level</p></article></section>
                @if ($user->role === 'Staff')
                    <section class="rounded-2xl border border-cyan-100 bg-cyan-50 p-5"><div class="flex flex-col gap-4 md:flex-row md:items-center md:justify-between"><div><p class="text-xs font-extrabold tracking-[.14em] text-[#0787bd]">STAFF WORKSPACE</p><h2 class="mt-1 text-xl font-black text-slate-900">Your operational checklist</h2><p class="mt-1 text-sm text-slate-500">Use the live station data below to prepare, confirm, and hand off today's water orders.</p></div><div class="flex gap-3"><a href="#orders" class="rounded-xl bg-[#0787bd] px-4 py-2.5 text-sm font-extrabold text-white">Review orders</a><a href="#deliveries" class="rounded-xl bg-white px-4 py-2.5 text-sm font-extrabold text-[#0787bd] ring-1 ring-cyan-200">Check deliveries</a></div></div></section>
                @endif
                <section class="grid gap-7 xl:grid-cols-5"><div id="orders" class="rounded-2xl bg-white p-5 shadow-sm ring-1 ring-slate-100 xl:col-span-3"><div class="mb-5"><h3 class="font-extrabold text-slate-900">Recent orders</h3><p class="text-xs text-slate-400">Newest station requests</p></div><div class="overflow-x-auto"><table class="w-full min-w-[540px] text-left text-sm"><thead class="border-b border-slate-100 text-xs uppercase tracking-wide text-slate-400"><tr><th class="pb-3 font-bold">Order</th><th class="pb-3 font-bold">Customer</th><th class="pb-3 font-bold">Amount</th><th class="pb-3 font-bold">Status</th></tr></thead><tbody class="divide-y divide-slate-100">@forelse($recentOrders as $order)<tr><td class="py-4 font-extrabold">#{{ str_pad((string) $order->order_id, 5, '0', STR_PAD_LEFT) }}</td><td class="py-4"><p class="font-bold">{{ $order->customer->customer_name }}</p><p class="text-xs text-slate-400">{{ $order->order_date->format('M j, g:i A') }}</p></td><td class="py-4 font-bold">₱{{ number_format((float) $order->total_amount, 2) }}</td><td class="py-4"><span class="rounded-full bg-cyan-50 px-2.5 py-1 text-xs font-bold text-cyan-700">{{ $order->order_status }}</span></td></tr>@empty<tr><td colspan="4" class="py-10 text-center text-sm text-slate-400">No orders have been recorded yet.</td></tr>@endforelse</tbody></table></div></div><div id="inventory" class="rounded-2xl bg-white p-5 shadow-sm ring-1 ring-slate-100 xl:col-span-2"><h3 class="font-extrabold text-slate-900">Inventory attention</h3><p class="mt-1 text-xs text-slate-400">Items at or below their reorder level</p><div class="mt-6 space-y-4">@forelse($lowStockItems as $item)<div class="flex items-center gap-3"><span class="grid h-10 w-10 place-items-center rounded-xl bg-amber-50 text-amber-600">◈</span><div class="min-w-0 flex-1"><div class="flex justify-between gap-2"><p class="truncate text-sm font-bold">{{ $item->item_name }}</p><span class="text-xs font-bold text-amber-600">{{ $item->quantity }} {{ $item->unit }}</span></div><div class="mt-2 h-1.5 overflow-hidden rounded-full bg-slate-100"><div class="h-full w-1/4 rounded-full bg-amber-400"></div></div></div></div>@empty<p class="rounded-xl bg-emerald-50 px-4 py-8 text-center text-sm font-semibold text-emerald-700">All inventory is within stock levels.</p>@endforelse</div></div></section>
                <section id="deliveries" class="rounded-2xl bg-white p-5 shadow-sm ring-1 ring-slate-100"><div class="mb-5"><h3 class="font-extrabold text-slate-900">Active deliveries</h3><p class="text-xs text-slate-400">Orders currently pending or in transit</p></div><div class="grid gap-4 md:grid-cols-2 xl:grid-cols-4">@forelse($deliveries as $delivery)<article class="rounded-xl border border-slate-100 p-4"><div class="flex justify-between gap-2"><span class="text-xs font-bold text-slate-400">#{{ str_pad((string) $delivery->order_id, 5, '0', STR_PAD_LEFT) }}</span><span class="rounded-full bg-amber-50 px-2 py-0.5 text-[11px] font-bold text-amber-700">{{ $delivery->delivery_status }}</span></div><p class="mt-3 font-extrabold">{{ $delivery->order->customer->customer_name }}</p><p class="mt-1 truncate text-xs text-slate-400">{{ $delivery->delivery_address }}</p><p class="mt-4 text-xs font-bold text-cyan-700">{{ $delivery->delivery_date?->format('M j · g:i A') ?? 'Schedule pending' }}</p></article>@empty<p class="md:col-span-2 xl:col-span-4 rounded-xl bg-slate-50 px-4 py-9 text-center text-sm text-slate-400">There are no active deliveries right now.</p>@endforelse</div></section>
            </div></main></div>
</body>
</html>
